# Generated by Django 4.2.6 on 2023-10-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationValue',
            fields=[
                ('configurationValueId', models.IntegerField(primary_key=True, serialize=False)),
                ('plant', models.CharField(max_length=4)),
                ('workCenter', models.CharField(max_length=10)),
                ('confgObject', models.CharField(max_length=50)),
                ('confgKey', models.CharField(max_length=50)),
                ('keyValue', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPullLog',
            fields=[
                ('autoId', models.IntegerField(primary_key=True, serialize=False)),
                ('plant', models.CharField(max_length=4)),
                ('materialNumber', models.CharField(max_length=18)),
                ('requestZoneId', models.CharField(max_length=100)),
                ('requestTimeStamp', models.DateTimeField()),
                ('acknowledgeTimeStamp', models.DateTimeField()),
                ('enrouteTimeStamp', models.DateTimeField()),
                ('deliveredTimeStamp', models.DateTimeField()),
                ('processed', models.CharField(max_length=1)),
                ('transferOrderNumber', models.CharField(max_length=20)),
                ('tagId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TagLog',
            fields=[
                ('tagId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('plant', models.CharField(max_length=4)),
                ('zoneId', models.CharField(max_length=10)),
                ('zoneEnteredTimeStamp', models.DateTimeField()),
                ('zoneExitTimeStamp', models.DateTimeField()),
                ('batteryPercentage', models.CharField(max_length=5)),
                ('transferOrderNumber', models.CharField(max_length=20)),
                ('materialNumber', models.CharField(max_length=18)),
                ('ZoneName', models.CharField(max_length=10)),
            ],
        ),
    ]
