# Generated by Django 4.2.6 on 2023-10-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationvalue',
            name='configurationId',
            field=models.IntegerField(default=0),
        ),
    ]
