# Generated by Django 4.2.6 on 2023-10-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0002_configurationvalue_configurationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationvalue',
            name='workCenter',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
