# Generated by Django 4.2.6 on 2023-11-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0004_alter_configurationvalue_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpulllog',
            name='transferOrderNumber',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
