# Generated by Django 4.2.6 on 2023-11-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0005_alter_materialpulllog_transferordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpulllog',
            name='autoId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
