# Generated by Django 4.2.6 on 2023-11-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0008_alter_materialpulllog_requesttimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpulllog',
            name='acknowledgeTimeStamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='materialpulllog',
            name='deliveredTimeStamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='materialpulllog',
            name='enrouteTimeStamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='materialpulllog',
            name='tagId',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
