# Generated by Django 4.2.6 on 2023-11-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0009_alter_materialpulllog_acknowledgetimestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpulllog',
            name='tagId',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
