# Generated by Django 4.2.6 on 2023-11-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0010_alter_materialpulllog_tagid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpulllog',
            name='transferOrderNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
