# Generated by Django 4.2.6 on 2023-11-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0013_alter_materialpulllog_transferordernumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taglog',
            name='plant',
        ),
    ]
