# Generated by Django 4.2.6 on 2023-11-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0014_remove_taglog_plant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taglog',
            old_name='ZoneName',
            new_name='zoneName',
        ),
    ]
