# Generated by Django 4.2.6 on 2023-11-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0015_rename_zonename_taglog_zonename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationvalue',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='configurationvalue',
            name='confgObject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='configurationvalue',
            name='plant',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='configurationvalue',
            name='workCenter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='materialpulllog',
            name='acknowledgeTimeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialpulllog',
            name='deliveredTimeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialpulllog',
            name='enrouteTimeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialpulllog',
            name='tagId',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
