# Generated by Django 4.2.6 on 2023-11-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0016_alter_configurationvalue_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationvalue',
            name='plant',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='taglog',
            name='zoneEnteredTimeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taglog',
            name='zoneExitTimeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
