# Generated by Django 4.2.6 on 2023-11-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0017_alter_configurationvalue_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationvalue',
            name='plant',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
