# Generated by Django 4.2.6 on 2023-11-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlsapp', '0018_alter_configurationvalue_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='taglog',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taglog',
            name='tagId',
            field=models.CharField(max_length=10),
        ),
    ]
